routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('command', function () {
	
	/* php artisan migrate */
    \Artisan::call('migrate:fresh --seed');
    dd("Done");
});

Route::group(['middleware' => ['role','share']], function(){
   
    Auth::routes();
    Route::resource('admin', 'Admin\AdminController');
    Route::get('/admin-index/{lang?}', 'Admin\AdminController@index')->name('admin.index');


    Route::resource('admin-mail', 'Admin\Mail\MailController');
    Route::get('/admin-mail-index/{lang?}', 'Admin\Mail\MailController@index')->name('admin-mail.index');
    
    Route::resource('group-email-template', 'Admin\Mail\GroupTemplateController');
    Route::get('/group-email-template-index/{lang?}', 'Admin\Mail\GroupTemplateController@index')->name('group-email-template.index');
    Route::put('/updateInUse/{id}', 'Admin\Mail\GroupTemplateController@updateInUse')->name('group-email-template.updateInUse');   


    Route::resource('email-template', 'Admin\Mail\TemplateController');


    Route::resource('admin-contact-form', 'Admin\ContactForm\ContactFormController');
    Route::get('/admin-contact-form-index/{lang?}', 'Admin\ContactForm\ContactFormController@index')->name('admin-contact-form.index');
    Route::get('/admin-contact-form-show/{id}/{lang?}', 'Admin\ContactForm\ContactFormController@show')->name('admin-contact-form.show');


    Route::resource('admin-user-management', 'Admin\UserManagement');
    Route::get('/admin-user-management-index/{lang?}', 'Admin\UserManagement@index')->name('admin-user-management.index');

    Route::resource('admin-general-settings', 'Admin\GeneralSettings');
    Route::get('/admin-general-settings-index/{lang?}', 'Admin\GeneralSettings@index')->name('admin-general-settings.index');

    Route::resource('admin-gender', 'Admin\GenderController');
    
    Route::resource('sessions', 'Client\SessionController');
    Route::get('/sessions/create/{lang?}/{id?}', 'Client\SessionController@create')->name('sessions.create');

    Route::resource('contact-form', 'Client\ContactFormController');
    



    
    Route::resource('admin-new-sessions', 'Admin\Session\NewSessions');
    Route::get('/admin-new-sessions-index/{lang?}', 'Admin\Session\NewSessions@index')->name('admin-new-sessions.index');
    Route::get('/admin-new-sessions-show/{id?}/{lang?}', 'Admin\Session\NewSessions@show')->name('admin-new-sessions.show');
    Route::get('/admin-new-sessions-new-advisor', 'Admin\Session\NewSessions@newAdvisor')->name('admin-new-sessions.newAdvisor');
    Route::put('/cancelNewSession/{id}', 'Admin\Session\NewSessions@cancelNewSession')->name('admin-new-sessions.cancelNewSession');
    Route::get('/get-user-google/{id}', 'Admin\Session\NewSessions@getUserGoogle')->name('admin-new-sessions.getUserGoogle');
    
    

    
    Route::resource('admin-sessions', 'Admin\Session\SessionController');
    Route::put('/endSession/{id}', 'Admin\Session\SessionController@endSession')->name('admin-sessions.endSession');
    Route::put('/cancelSession/{id}', 'Admin\Session\SessionController@cancelSession')->name('admin-sessions.cancelSession');
    
    
    
    Route::resource('admin-finished-sessions', 'Admin\Session\FinishedSessions');
    Route::get('/admin-finished-sessions-index/{lang?}', 'Admin\Session\FinishedSessions@index')->name('admin-finished-sessions.index');
    Route::get('/admin-finished-sessions-show/{id?}/{lang?}', 'Admin\Session\FinishedSessions@show')->name('admin-finished-sessions.show');


    
    Route::resource('admin-new-projects', 'Admin\Project\NewProjectsController');
    Route::get('/admin-new-projects-index/{lang?}', 'Admin\Project\NewProjectsController@index')->name('admin-new-projects.index');
    
    Route::resource('admin-projects', 'Admin\Project\ProjectsController');
    Route::get('/admin-projects-index/{lang?}', 'Admin\Project\ProjectsController@index')->name('admin-projects.index');
    Route::get('/admin-projects-show/{id?}/{lang?}', 'Admin\Project\ProjectsController@show')->name('admin-projects.show');
    Route::get('/admin-projects-new-advisor', 'Admin\Project\ProjectsController@newAdvisor')->name('admin-projects.newAdvisor');
    Route::post('/admin-projects-add-raport', 'Admin\Project\ProjectsController@addRaport')->name('admin-projects.addRaport');
    
    
    Route::resource('admin-tasks', 'Admin\TasksController');
    Route::get('/admin-tasks-index/{lang?}', 'Admin\TasksController@index')->name('admin-tasks.index');



    Route::resource('admin-contact', 'Admin\Contacts\ContactCompanyController');
    Route::get('/admin-contact-index/{lang?}', 'Admin\Contacts\ContactCompanyController@index')->name('admin-contact.index');

    Route::resource('admin-contact-settings', 'Admin\Contacts\ContactSettingsController');
    Route::get('/admin-contact-settings-index/{lang?}', 'Admin\Contacts\ContactSettingsController@index')->name('admin-contact-settings.index');
    
    Route::resource('admin-contact-settings', 'Admin\Contacts\EmailTypeController');
    


    Route::resource('admin-calendar', 'Admin\Calendar\CalendarController');
    Route::get('/admin-calendar-index/{lang?}', 'Admin\Calendar\CalendarController@index')->name('admin-calendar.index');
    
    
    Route::resource('admin-google-controller', 'Admin\Calendar\GoogleController');
    Route::get('/admin-calendar-google-store/oauth', 'Admin\Calendar\GoogleController@store')->name('admin-google-controller.store');
    Route::delete('/admin-calendar-google-store/{googleAccount}', 'Admin\Calendar\GoogleController@destroy')->name('admin-google-controller.destroy');


    Route::resource('admin-event', 'Admin\Calendar\EventController');
    Route::get('/admin-event-edit/{id?}', 'Admin\Calendar\EventController@edit')->name('admin-event.edit');
    Route::delete('/admin-event-destroy/{id?}', 'Admin\Calendar\EventController@destroy')->name('admin-event.destroy');
    Route::put('/admin-event-update/{id?}', 'Admin\Calendar\EventController@update')->name('admin-event.update');
   
    

    Route::resource('moderator', 'Moderator\ModeratorController');
    Route::get('/moderator-index/{lang?}', 'Moderator\ModeratorController@index')->name('moderator.index');
    
    


    
    Route::resource('consultant', 'Consultant\ConsultantController');
    Route::get('/consultant-index/{lang?}', 'Consultant\ConsultantController@index')->name('consultant.index');



    Route::resource('consultant-sessions', 'Consultant\SessionsController');
    Route::get('/consultant-sessions-show/{id?}/{lang?}', 'Consultant\SessionsController@show')->name('consultant-sessions.show');
    Route::get('/consultant-sessions-create/{lang?}', 'Consultant\SessionsController@create')->name('consultant-sessions.create');
    Route::put('/endConsultantSession/{id}', 'Consultant\SessionsController@endSession')->name('consultant-sessions.endSession');
    Route::put('/cancelConsultantSession/{id}', 'Consultant\SessionsController@cancelSession')->name('consultant-sessions.cancelSession');
   
    Route::resource('consultant-finished-sessions', 'Consultant\FinishedSessionsController');
    Route::get('/consultant-finished-sessions-index/{lang?}', 'Consultant\FinishedSessionsController@index')->name('consultant-finished-sessions.index');
    Route::get('/consultant-finished-sessions-show/{id?}/{lang?}', 'Consultant\FinishedSessionsController@show')->name('consultant-finished-sessions.show');
    

    

    
    Route::get('/home/{lang?}', 'HomeController@index')->name('home');
    Route::get('/{lang?}', 'PagesController@wellcome')->name('wellcome');
});


      
        
      

app/Http/Controllers/Admin/Session/FinishedSessions.php
<?php

namespace App\Http\Controllers\Admin\Session;

use App;
use App\User;
use App\Langs;
use App\Gender;
use App\ContactForm;
use App\SesionConsultant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FinishedSessions extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($langSysName = "")
    { 
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }else{
            $lang=Langs::where('system_name',$langSysName)->first();
            if(!$lang){
                $langSysName = config('app.fallback_locale'); 
            }else{
                $langSysName = $lang->system_name;
            }
        }
        App::setLocale($langSysName);

        $mails = ContactForm::where('status',3)->paginate(20);
        return view('admin.finished-sessions.index', compact('mails'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id = "", $langSysName = "")
    {
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }else{
            $lang=Langs::where('system_name',$langSysName)->first();
            if(!$lang){
                $langSysName = config('app.fallback_locale'); 
            }else{
                $langSysName = $lang->system_name;
            }
        }
        App::setLocale($langSysName);
        $genders = Gender::get();
        $mail = ContactForm::find($id);
        $users = User::all();
        return view('admin.finished-sessions.show',compact('mail','genders','users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Consultant/ConsultantController.php
<?php

namespace App\Http\Controllers\Consultant;

use App;
use App\User;
use App\Langs;
use App\Gender;
use App\Session;
use App\ContactForm;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ConsultantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($langSysName = "")
    {
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }else{
            $lang=Langs::where('system_name',$langSysName)->first();
            if(!$lang){
                $langSysName = config('app.fallback_locale'); 
            }else{
                $langSysName = $lang->system_name;
            }
        }
        App::setLocale($langSysName);
        return view('consultant.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Consultant/FinishedSessionsController.php
<?php

namespace App\Http\Controllers\Consultant;

use App;
use App\User;
use App\Langs;
use App\Gender;
use App\Session;
use App\ContactForm;
use App\SesionConsultant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FinishedSessionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($langSysName = "")
    { 
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }else{
            $lang=Langs::where('system_name',$langSysName)->first();
            if(!$lang){
                $langSysName = config('app.fallback_locale'); 
            }else{
                $langSysName = $lang->system_name;
            }
        }
        App::setLocale($langSysName);

        $mails = ContactForm::where('status',3)->paginate(20);
        return view('consultant.finished-sessions.index', compact('mails'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id = "", $langSysName = "")
    {
        if($langSysName == ""){
            $langSysName = config('app.fallback_locale'); 
        }else{
            $lang=Langs::where('system_name',$langSysName)->first();
            if(!$lang){
                $langSysName = config('app.fallback_locale'); 
            }else{
                $langSysName = $lang->system_name;
            }
        }
        App::setLocale($langSysName);
        $genders = Gender::get();
        $mail = ContactForm::find($id);
        $users = User::all();
        return view('consultant.finished-sessions.show',compact('mail','genders','users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/consultant/finished-sessions/index.blade.php
@extends('layouts.consultant')

@section('content')
<div class="container-fluid">
    <h4>
        <i class="far fa-thumbs-up mr-2"></i>Ended sessions
    </h4>
    <hr>
    <div class="row text-white mx-1 bg-dark">
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
            Client name
        </div>
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
           Advisors
        </div>
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
            Seasson date
        </div>
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
            Seasson time start
        </div>
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
            Seasson time end
        </div>
        <div class="pointer a-redirect p-2 text-center border-bottom col-md">
            Price
        </div>
    </div>
    @foreach ($mails as $mail)
    @if(count($mail->session->consultants) != 0 && $mail->session->price!=null)
    <div data-redirect-url="{{route('consultant-finished-sessions.show',['id'=>$mail->id,'lang'=>App::getLocale()])}}"
        class="row mx-1 bg-light bg-light-hover">

        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            {{$mail->name}}
        </div>
        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            @foreach ($mail->session->consultants as $consultant)
            <div class="row">
                <div class="col-md-12">
                    {{$consultant->user->name}}
                </div>
            </div>
            @endforeach
        </div>
        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            {{$mail->session->date}}
        </div>
        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            {{$mail->session->time_start}}
        </div>
        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            {{$mail->session->time_end}}
        </div>
        <div class="pointer h7 a-redirect p-2 text-center border-bottom col-md">
            {{$mail->session->price}} euro
        </div>
    </div>
    @endif
    @endforeach
</div>
@endsection

resources/views/consultant/finished-sessions/show.blade.php
@extends('layouts.consultant')

@section('content')
<div class="container-fluid mb-5">
    <h4>
        <i class="far fa-thumbs-up mr-2"></i>Ended sessions
    </h4>
    <hr>

    <form data-url="{{ route('admin-sessions.update',$mail->id) }}" id="session-confirm-form">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h4>Client Info</h4>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-5">
                <label for="session-client-infor-name">Client name</label>
                <input value="{{$mail->name}}" id="session-client-infor-name" class="form-control" type="text" readonly>
            </div>
            <div class="col-md-5">
                <label for="session-client-infor-email">Email address</label>
                <input value="{{$mail->email}}" id="session-client-infor-email" class="form-control" type="text" readonly>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-5">
                <label for="session-client-infor-phone">Phone number</label>
                <input value="{{$mail->phone}}" id="session-client-infor-phone" class="form-control" type="text" readonly>
            </div>
            <div class="col-md-5">
                <label for="session-client-infor-address">Address</label>
                <input value="{{$mail->address}}" id="session-client-infor-address" placeholder="Address"
                    class="form-control" type="text" readonly>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-5">
                <label for="session-client-infor-birth_date">Birth date</label>
                <input value="{{$mail->birth_date}}" id="session-client-infor-birth_date" placeholder="Birth date"
                    class="form-control" type="date" readonly>
            </div>
            <div class="col-md-5">
                <label for="session-client-infor-gender">Gender</label>
                <select name="" id="session-client-infor-gender" class="form-control rounded-0" id="my-select">
                    <option value="" selected disabled>Gender</option>
                    @foreach ($genders as $gender)
                    <option value="{{$gender->id}}" @if($gender->id == $mail->gender_id) selected
                        @endif>{{$gender->genderTrans(App::getLocale())->name}}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-md-10">
                <label for="exampleInputEmail1">Contact message</label>
                <p>{{$mail->description}}</p>
            </div>
        </div>
        @if(isset($mail->response))
        <div class="row mt-3 justify-content-center">
            <div class="col-md-10">
                <h4 class="m-0">Manager's response</h4>
            </div>
        </div>

        <div class="row mt-1 mb-3 justify-content-center">
            <div class="col-md-10">
                <p class="my-1"><span class="font-weight-bold mr-2">Subject:</span>{{$mail->response->title}}</p>
                <p class="my-1"><span class="font-weight-bold mr-2">Email:</span></p>
                {!!$mail->response->description!!}
            </div>
        </div>
        @endif

        @if(isset($mail->session))
        <div class="row mt-5 justify-content-center">
            <div class="col-md-10">
                <h4>Information about the reserved session</h4>
            </div>
        </div>

        <div class="row mt-2 justify-content-center">
            <div class="col-md-10">
                <div class="row mx-1 bg-dark text-white">
                    <div class="pointer p-2 text-center border-bottom col-md">
                        Date
                    </div>
                    <div class="pointer p-2 text-center border-bottom col-md">
                        Time when the session starts
                    </div>
                    <div class="pointer p-2 text-center border-bottom col-md">
                        Time when the session ends
                    </div>
                </div>
                <div class="row mb-4 mx-1 bg-light bg-light-hover">
                    <div class="pointer p-2 text-center border-bottom col-md">
                        {{$mail->session->date}}
                    </div>
                    <div class="pointer p-2 text-center border-bottom col-md">
                        {{$mail->session->time_start}}
                    </div>
                    <div class="pointer p-2 text-center border-bottom col-md">
                        {{$mail->session->time_end}}
                    </div>
                </div>
            </div>
        </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h4>Advisors Enrollment</h4>
            </div>
        </div>

        <div class="row mt-2 justify-content-center">
            <div id="advisor-list" class="col-md-10">
                @foreach ($mail->session->consultants as $consultant)
                <div class="mb-2 row justify-content-center">
                    <div class="col-md-5">
                        <select name="" id="" class="advisor-engagement-select form-control">
                            @foreach ($users as $user)
                            @if($user->id == $consultant->user_id)<option value="{{$user->id}}" selected>{{$user->name}}</option>@endif
                            @endforeach
                        </select>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group mb-3">
                            <input type="number" value="{{$consultant->engagement_rate}}"
                                class="advisor-engagement-percentage form-control"
                                aria-label="advisor engagement percentage" readonly>
                            <div class="input-group-append">
                                <span class="input-group-text">%</span>
                            </div>
                        </div>
                    </div>
                </div>

                @endforeach
            </div>
        </div>


        <div class="row mt-4 justify-content-center">
            <div class="col-md-10">
                <h4>Session price</h4>
            </div>
        </div>

        <div class="row mt-1 justify-content-center">
            <div class="col-md-6">
                <div class="input-group mb-3">
                    <input type="number" class="form-control" id="session-price" value="{{$mail->session->price}}" readonly>
                    <div class="input-group-append">
                        <span class="input-group-text">€</span>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection